USE StudentManagement ; 
CREATE MASTER KEY ENCRYPTION BY
PASSWORD = 'USER123' ;

CREATE TABLE loginInfo
(ID int,
staffID int,
password varbinary (50)
)

CREATE CERTIFICATE MyCert1
 WITH SUBJECT = 'passwords';

 GO

 CREATE SYMMETRIC KEY SSN_KEY_01
	WITH ALGORITHM = AES_256
	ENCRYPTION BY CERTIFICATE MyCert1;
GO

OPEN SYMMETRIC KEY SSN_KEY_01
	DECRYPTION BY CERTIFICATE MyCert1;
INSERT INTO loginInfo VALUES
(1, 12345, ENCRYPTBYKEY(KEY_GUID('SSN_Key_01'), password))

OPEN SYMMETRIC KEY SSN_KEY_01
	DECRYPTION BY CERTIFICATE MyCert1;

SELECT *,
CONVERT (varchar, DECRYPTBYKEY(password)) AS [Decrypted password]
	FROM loginInfo


CLOSE SYMMETRIC KEY SSN_KEY_01